### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by TX-QAQ** [tencentyun/wafer-node-session#1]
只要在app.js中一加入const waferSession = require('wafer-node-session'); 这一行

服务器就无法正常运行，查看log:
[STREAMING] Now streaming realtime logs for [app] process
0|app      | SyntaxError: Unexpected token {
0|app      |     at exports.runInThisContext (vm.js:53:16)
0|app      |     at Module._compile (module.js:374:25)
0|app      |     at Object.Module._extensions..js (module.js:417:10)
0|app      |     at Module.load (module.js:344:32)
0|app      |     at Function.Module._load (module.js:301:12)
0|app      |     at Module.require (module.js:354:17)
0|app      |     at require (internal/module.js:12:17)
0|app      |     at Object.<anonymous> (/data/release/weapp/app.js:2:22)
0|app      |     at Module._compile (module.js:410:26)
0|app      |     at Object.Module._extensions..js (module.js:417:10)

**Comment by techird** [comment]
目测你的 Node 版本比较旧导致，可以方便说一下你的 Node 版本吗？

**Comment by TX-QAQ** [comment]
node -v
v4.2.6

**Comment by TX-QAQ** [comment]
我用apt-get装的，没有用教程里的yum

**Comment by techird** [comment]
Node 版本确实老了，需要 Node 6 以上，建议使用 Node 7
